// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"io"
)

const (
	home__0 = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><title>`
	home__1 = `</title><link rel="stylesheet" href="/css/main.css"/><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"/><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/></head><body><nav class="navbar navbar-expand-lg navbar-light bg-light"><div class="container"><a class="navbar-brand" href="./">Website Walid</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div id="navbarSupportedContent" class="collapse navbar-collapse"><ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item"><a class="nav-link active" aria-current="page" href="./">Home</a></li>`
	home__2 = `</ul><form class="d-flex"><input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/><button class="btn btn-outline-success" type="submit">Search</button></form></div></div></nav><div class="container"><h1>Jade - template engine</h1><div id="container" class="col">`
	home__3 = `<p>                    Jade/Pug is a terse and simple
                    templating language with
                    a <strong>focus</strong> on performance 
                    and powerful features.</p><footer><div class="footer">2021</div></footer></div></div></body></html>`
	home__4 = `<li class="nav-item"></li><a class="nav-link" href="./admin">Admin</a><a class="nav-item nav-link" href="./login">Logout (`
	home__5 = `)</a>`
	home__6 = `<a class="nav-item nav-link" href="./login">Login</a>`
	home__7 = `<p>You are amazing</p>`
	home__8 = `<p>Get on it!</p>`
)

func home(pageTitle, user string, signIn bool, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(home__0)
	WriteEscString(pageTitle, buffer)
	buffer.WriteString(home__1)

	if signIn {
		buffer.WriteString(home__4)
		WriteEscString(user, buffer)
		buffer.WriteString(home__5)

	} else {
		buffer.WriteString(home__6)

	}
	buffer.WriteString(home__2)

	if signIn {
		buffer.WriteString(home__7)

	} else {
		buffer.WriteString(home__8)

	}
	buffer.WriteString(home__3)

}
